name: Enforce repository settings

on:
  push:
    branches:
      - main

jobs:
  probot-settings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run probot-settings

      uses: elstudio/actions-settings@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
